# Generated by Django 4.2.2 on 2023-07-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('asignada', 'Asignada'), ('vista', 'Vista'), ('completada', 'Completada'), ('en reasignación', 'En reasignación'), ('anulada', 'Anulada')], default='asignada', max_length=15, verbose_name='Estado de la actividad'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre de la actividad'),
        ),
    ]
