# Generated by Django 4.2.2 on 2023-07-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tarea_observaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='prioridad',
        ),
        migrations.AddField(
            model_name='tarea',
            name='categoria',
            field=models.CharField(choices=[('trabajo', 'trabajo'), ('casa', 'casa'), ('estudio', 'estudio'), ('etc', 'etc')], default='casa', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tarea',
            name='fecha_creacion',
            field=models.DateField(auto_now=True),
        ),
    ]
