# Generated by Django 4.2.2 on 2023-07-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_tarea_prioridad_tarea_categoria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='descripcion',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
