# Generated by Django 4.2.2 on 2023-07-12 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_tarea_descripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='descripcion',
        ),
    ]
